### ISSUE TITLE
Downloading raw files: Fail @ first step

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/Paper-DNR-Geoduck-Proteomics#14]
I opened a new R script in R studio and pasted in your code. Got an error after running the first line.

<img width="610" alt="screen shot 2017-10-11 at 9 26 09 pm" src="https://user-images.githubusercontent.com/22335838/31479272-e62d04e4-aeca-11e7-8787-39b1713a29a4.png">

<img width="1278" alt="screen shot 2017-10-11 at 9 27 05 pm" src="https://user-images.githubusercontent.com/22335838/31479279-f3ff9a6e-aeca-11e7-97a2-a60f0c881fc8.png">

**Comment by yaaminiv** [comment]
Downloaded your full repo and opened the script. Same error.

<img width="792" alt="screen shot 2017-10-11 at 10 02 41 pm" src="https://user-images.githubusercontent.com/22335838/31479978-edb2b4ac-aecf-11e7-9015-1f082cf962d9.png">

**Comment by yaaminiv** [comment]
I believe there's an issue with your relative path. The following code worked for me:

`dir.create("./Downloads/2017-Geoduck-SRM-raw")`

Not sure how this syntax affects the rest of your code/anything downstream, or if this is an artifact of how my computer is organized? I'll wait for you to resolve this before proceeding!

**Comment by laurahspencer** [comment]
Thanks! definitely a relative path issue; I tried your suggestion on the Windows computer but no go. I'm curious if the multiple users is causing an issue... something I'll ask tomorrow.

**Comment by yaaminiv** [comment]
Now that I think about it, where I choose to download your paper repo on my local machine will dictate the relative path to the Downloads folder. Why not just have someone download the RAW files into a working directory in the repo? Is there some advantage to having them download the files elsewhere?

**Comment by laurahspencer** [comment]
Modified to simply create a folder and move to that folder to download .raw files:  [edited Script 00](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/analyses/SRM/00-Downloading-raw-files.R)

**Comment by sr320** [comment]
Note this should have been closed by @yaaminiv if in fact it worked.... it appears to not have resolved the issue
