### ISSUE TITLE
Step 3- my analyte tree is slightly different than yours

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/Paper-DNR-Geoduck-Proteomics#16]
At Step 3, it is suggested that I use a text reader to copy/paste the analyte tree. When I tried this with Notepad ++, things got weird! 
![capture-g](https://user-images.githubusercontent.com/14934314/31958928-27cb5cac-b8a8-11e7-9c6c-dd5c582768d2.PNG)

And when I tried to paste that into skyline, it said:
![capture-g2](https://user-images.githubusercontent.com/14934314/31959584-f48fe946-b8a9-11e7-910f-e81fe3bcda3e.PNG)

What I did instead was selected to view the "Raw" of your .fasta in GitHub and copy and pasted that and it worked easily. 

I did notice, though, that my analyte tree says "Heat", while yours says "HSP70": So maybe my method was wrong?
![capture-g3](https://user-images.githubusercontent.com/14934314/31959796-8ddd15b0-b8aa-11e7-80b5-a71f1e8eb4cf.PNG)
![capture-g4](https://user-images.githubusercontent.com/14934314/31959797-8df5e7d4-b8aa-11e7-8cd6-902a3148caf7.PNG)

**Comment by kubu4** [comment]
I'm guessing you downloaded this file from GitHub? If yes, you need to download the file using the "Raw" button when you are viewing the file on GitHub.

**Comment by grace-ac** [comment]
Yes, and yes I did download from the "Raw" view!

**Comment by kubu4** [comment]
Can you post link to protocol and the repo that you pulled this file from?

**Comment by grace-ac** [comment]
Link to .fasta file: [here](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/data/SRM/2017-geoduck-SRM-targets.fasta)

Protocol link: [here](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/notebooks/SRM/01-Create-Skyline-Project.md#step-3-populate-analyte-tree-aka-add-your-srm-target-proteins-to-targets-pane)

**Comment by laurahspencer** [comment]
Weird notepad issue.
You did the correct thing, I think I just changed the name manually from
Heat to HSP70 in the analyze tree (just like editing a file name in a
directly, right click, or click twice, edit name).

This is reminding me that I should update this step, as per a suggestion
from Yaamini. Instead of using the fasta file with my targeted proteins I
can use a list of targeted transitions, so there's no need to delete
not-targeted transitions/peptides.

In any case you did things correctly, just edit the "heat" name to HSP70
for now in order to move forward with the analysis.

Thanks!

**Comment by kubu4** [comment]
>Yes, and yes I did download from the "Raw" view!

The posted screenshot isn't downloaded from the "Raw" view; that's why you got the error in Skyline when you copied/pasted. 

Isn't that what this issue is about?

**Comment by kubu4** [comment]
To fix the problem you experienced, the link to the FASTA file needs to be changed to: https://raw.githubusercontent.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/master/data/SRM/2017-geoduck-SRM-targets.fasta

Instructions will also need to be added to right-click on the link and "Save link as..."

**Comment by grace-ac** [comment]
Oh, I just said in words that I downloaded from the Raw view. The screenshot is of something weird that happened with notepad ++ 

The issue was just that my analyte tree ended up looking a little different than Laura's so I detailed how I got to that tree. But didn't include a screenshot of the copying and pasting from the Raw.

Just tried your link and "save link as..." and the problem was fixed! Still read as "Heat" rather than "HSP70, but that can be changed.

**Comment by kubu4** [comment]
Oh, duh. I see the issue title! However, your screenshots pointed to another issue that needed to be addressed; serendipity at its finest!

**Comment by laurahspencer** [comment]
Great, here are things I will update as per the feedback: 
  * Change all my file hyperlinks to link directly to to the raw version, instructing the user to save-as.
  * Change the analyte populating step to use the list of targeted transitions, and not the full protein fasta.  This change will not require you to remove any non-targeted peptides, AND I can control how the names show up on the analyte tree.

**Comment by kubu4** [comment]
@laurahspencer - before you change all the URLs, maybe wait until we can discuss this [issue at lab meeting](https://github.com/RobertsLab/resources/issues/103)?
