### ISSUE TITLE
Deeming GO-terms significant  

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/Paper-DNR-Geoduck-Proteomics#19]
As discussed last Wednesday, I need to determine which GO terms are significant from my DAVID results. Here are 2 spreadsheets downloaded from DAVID: 

1. [GO Terms >2x more abundant in Northern Sites](https://raw.githubusercontent.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/master/analyses/DIA/DIA_GO-Terms_FoldChange2-North.txt)
2. [GO Terms >2x more abundant in Southern Sites ](https://raw.githubusercontent.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/master/analyses/DIA/DIA_GO-Terms_FoldChange2-South.txt)

@sr320 can you help me understand which metric I should use for significance? I see there is a PValue column, but also Bonferroni & other multiple comparison corrected values - with very different significance.

**Comment by sr320** [comment]
You want Benjamini-Hochberg adjusted p<0.05. (Accounts for multiple tests).

![ex](http://eagle.fish.washington.edu/cnidarian/skitch/DIA_GO-Terms_FoldChange2-South_and_DIA_GO-Terms_FoldChange2-North_and_Deeming_GO-terms_significant_·_Issue__19_·_RobertsLab_Paper-DNR-Geoduck-Proteomics_2033058D.png)

**Comment by laurahspencer** [comment]
Thanks, this makes the DIA analysis decision easy.
