### ISSUE TITLE
Files not in Downloads Directory

### ISSUE THREAD

**Issue by sr320** [RobertsLab/Paper-DNR-Geoduck-Proteomics#6]
Disconnect in protocol...

![image](https://user-images.githubusercontent.com/4442039/31295972-7e65ff5c-aa95-11e7-8f33-dac38ec2d043.png)

**Comment by laurahspencer** [comment]
Thanks- somehow the first few lines of the script had been deleted. I've updated- try now

**Comment by grace-ac** [comment]
New script worked for me! 
![screen shot 2017-10-06 at 2 23 08 pm](https://user-images.githubusercontent.com/14934314/31299166-fbb0488a-aaa1-11e7-99ef-eeec7f9fba6d.png)
