### ISSUE TITLE
importing .raw into Skyline

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/Paper-DNR-Geoduck-Proteomics#7]
Step 5, [Notebook 01-Create-Skyline-Project.md](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/notebooks/SRM/01-Create-Skyline-Project.md)
"a box will pop up giving you the option to remove extraneous info for each replicate". 

The box did not pop up for me:
![capture3](https://user-images.githubusercontent.com/14934314/31359692-e8adba50-acff-11e7-9dbb-4ef55d302151.PNG)

Then, after finding the folder of .raw in the "Downloads" of srlab, it looked like this:
![capture4](https://user-images.githubusercontent.com/14934314/31359719-022cbba2-ad00-11e7-822a-33d097abf1bd.PNG)

After selecting all of the .raw files, the original box you mention (for removing extraneous info...) popped up. 

Maybe not super crucial, but I was confused for a bit as to why that box didn't pop up. Might be helpful to reorder the guide a little! 

.raw are currently downloading and things look good so far!

**Comment by laurahspencer** [comment]
I added a line & screen shot to the protocol that describes navigating to the folder containing the .raw files, and selecting. Thanks, I hope this helps!
