### ISSUE TITLE
Step 6: Rearrange Skyline Window- doesn't look like yours

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/Paper-DNR-Geoduck-Proteomics#8]
Here's what my skyline daily window looks like after rearranging according to the protocol: 
![capture2](https://user-images.githubusercontent.com/14934314/31362326-b146e91c-ad0c-11e7-8d5e-9e5c719e85d7.PNG)

Particularly the lefthand target area. Mine has a whole lot more going on.
Is there something else I should do to get it to look like your screenshot at the bottom of Notebook [01-Create-Skyline-Project.md](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/notebooks/SRM/01-Create-Skyline-Project.md) ?

**Comment by laurahspencer** [comment]
I provided more details and included a short video in the notebook; let me know if things are still unclear

**Comment by grace-ac** [comment]
The video is awesome!
